version: '2'

services:
  gateone:
    build: .
    image: zhicwu/gateone${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    command: gateone
    ports:
      - "${SERVER_PORT}:8000"
    volumes:
      - ./data/cache:/gateone/.cache:rw
      - ./data/logs:/gateone/.gateone/logs:rw
      - ./data/sessions:/gateone/.gateone/sessions:rw
    environment:
      HOST_USER_ID: ${HOST_USER_ID}
      URL_PREFIX: /ssh/
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    restart: always
